### ISSUE TITLE
Question: OpenAI embeddings

### ISSUE THREAD

**Issue by claudeomusic** [timescale/pgai#185]
This is more a question than a comment - curious if it's on your roadmap to explore other embedding models outside of OpenAI or perhaps making it configurable? 

Love this work - just a very real consideration for many of us to be able to opt in/opt out of models

**Comment by alejandrodnm** [comment]
Hey @claudeomusic. The pgai postgres extension supports many functions for multiple AI providers https://github.com/timescale/pgai/tree/main/docs 

For the Vectorizer feature we've just launched, we only have support OpenAI and its models, but yes we plan to support other providers, and we also accept PRs from the community :)
