### ISSUE TITLE
How to use pgai with PostgreSQL v17?

### ISSUE THREAD

**Issue by sfkeller** [timescale/pgai#193]
### What problem does the new feature solve?

I'd like to use pgai with PostgreSQL - currently v17 - citing the pgai README title "pgai allows you to develop (...) directly in PostgreSQL" and the pgai LICENSE ("The PostgreSQL License"). 

How?

### What does the feature do?

See above. Don't know if this is a request for documentation or feature.

### Implementation challenges

Don't see any dependencies with TimescaleDB.

### Are you going to work on this feature?

None

**Comment by Askir** [comment]
Hi @sfkeller,
The timescale-db image is a normal postgres installation, with additional extensions like timescale and pgai available. You can use it as is (although we do not have an image for PG17 yet).

Alternatively the readme lists how you can install pgai from source on a PG server (or build your own image for that matter): https://github.com/timescale/pgai?tab=readme-ov-file#install-from-source 
This hasn't been tried on pg17 as far as I know, but I also don't know why it wouldn't work. So feel free to give it a shot and report back.
