### ISSUE TITLE
[Bug]: <Title>

### ISSUE THREAD

**Issue by mikeharlow** [timescale/pgai#297]
### What happened?

I am following your just installation process on Ubuntu.  It looks like a file is missing in  pgai/projects/extension/sql/ai--0.6.1-dev.sql?

### pgai extension affected

0.6.1

### PostgreSQL version used

16

### What operating system did you use?

Ubuntu 24.04

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
required sql file is missing: /home/usr/pgai/projects/extension/sql/ai--0.6.1-dev.sql
```

### How can we reproduce the bug?

```bash
git clone https://github.com/timescale/pgai.git
cd pgai
just ext install
```

### Are you going to work on the bugfix?

None

**Comment by JamesGuthrie** [comment]
can you try `just ext build; just ext install`?

**Comment by jgpruitt** [comment]
You are installing a development version: `0.6.1-dev`. Are you sure that's what you want?

**Comment by jgpruitt** [comment]
If you want the latest production version, check out the repo at the `extension-0.6.0` tag. Then, `just ext install` will "just work".
https://github.com/timescale/pgai/releases/tag/extension-0.6.0

**Comment by mikeharlow** [comment]
Thank you, pulling the 0.6.0 extension branch solved the error.  I was following instructions from claude.ai.
