### ISSUE TITLE
ModuleNotFoundError: No module named 'ai', even though installed in virtualenv, turns out it goes to /usr/local/lib/pgai

### ISSUE THREAD

**Issue by SamuelMarks** [timescale/pgai#65]
Being careful to install pgai in a virtualenv, I was surprised to get this in my log:
```
2024-08-24 22:13:34.949 UTC [62] ERROR:  error fetching next item from iterator
2024-08-24T22:13:34.949976795Z 2024-08-24 22:13:34.949 UTC [62] DETAIL:  ModuleNotFoundError: No module named 'ai'
2024-08-24T22:13:34.949987966Z 2024-08-24 22:13:34.949 UTC [62] CONTEXT:  Traceback (most recent call last):
2024-08-24T22:13:34.949996472Z 	PL/Python function "openai_list_models"
2024-08-24T22:13:34.950005008Z 2024-08-24 22:13:34.949 UTC [62] STATEMENT:  SELECT *
2024-08-24T22:13:34.950016911Z 	FROM ai.openai_list_models
```

Replicate here:
```dockerfile
ARG PG_MAJOR=16

FROM postgres:${PG_MAJOR}-alpine AS builder
ARG PG_MAJOR
ARG PGVECTOR=1
ARG PGVECTOR_VER="0.7.4"
ARG PGAI=1

RUN apk add --no-cache \
    bison \
    build-base \
    cargo \
    clang15 \
    cmake \
    flex \
    git \
    linux-headers \
    llvm15 \
    make \
    openblas-dev \
    perl \
    pkgconf \
    "postgresql${PG_MAJOR}-plpython3" \
    "postgresql${PG_MAJOR}-dev" \
    py3-pip \
    python3-dev \
    readline-dev \
    tzdata \
    zlib-dev

WORKDIR /tmp/wd

ADD "https://github.com/pgvector/pgvector/archive/refs/tags/v${PGVECTOR_VER}.tar.gz" .

RUN if [ "${PGVECTOR}" -eq 1 ]; then \
      tar xf v${PGVECTOR_VER}.tar.gz && \
      cd "pgvector-${PGVECTOR_VER}" && \
      make clean && \
      make OPTFLAGS="" && \
      make install && \
      mkdir -p /usr/share/doc/pgvector && \
      cp LICENSE README.md /usr/share/doc/pgvector ; \
    fi

RUN if [[ "${PGAI}" -eq 1 && "${PGVECTOR}" -eq 1 ]]; then \
      git clone --depth=1 --single-branch https://github.com/timescale/pgai && \
      python3 -m venv /opt/venv && . /opt/venv/bin/activate && \
      cd pgai && \
      make install ; \
    fi

# my real dockerfile installs other extensions and is a multi-stage build that `COPY`ies, then does:

STOPSIGNAL SIGINT

EXPOSE 5432

ENV PYTHONPATH="/opt/venv/lib/python3.12/site-packages"
ENV VIRTUAL_ENV="/opt/venv"

CMD ["postgres"]
```

Doing a `find` I found `/usr/local/lib/pgai/0.4.0/ai/__init__.py`. That's the wrong location?

**Comment by jgpruitt** [comment]
It looks like you're installing from the `main` branch which is as-yet unreleased. [v0.3.0](https://github.com/timescale/pgai/releases/tag/v0.3.0) is the latest released version.

The postgres server has to be able to find any dependencies referenced by the plpython3u functions. In versions 0.1.0, 0.2.0, 0.3.0, the Python dependencies were installed into the system site dir. This isn't great.

In the upcoming release, we will install our python code plus dependencies under /usr/local/lib/pgai/<version>/. Our plpython3u functions will then automatically find the right directory and use `site.addsitedir()`.

**Comment by SamuelMarks** [comment]
@jgpruitt Yes and I do the `COPY` here https://github.com/SamuelMarks/postgres-extended-builds/blob/2cba875/alpine.Dockerfile#L128

The question is about making these virtualenvs independent of the system. E..g, for multiple installed PostgreSQL and pgai versions.

**Comment by jgpruitt** [comment]
Ah, I see. Hmm.

When you install pgai, it will install ALL supported versions of itself. So, you'll end up with (for example):

- /usr/local/lib/pgai/0.4.0/
- /usr/local/lib/pgai/0.5.0/
- /usr/local/lib/pgai/1.0.0/
- etc.

These are the python dependencies and code for each version of pgai and will be independent of postgres version. i.e. /usr/local/lib/pgai/0.4.0/ will work with postgres 16, 17, 18.

So, if you have 0.4.0 installed on postgres 16 and 0.5.0 installed on postgres 17 on the same box, you should be good to go with this paradigm. And when you want to upgrade from 0.4.0 to 0.5.0 in postgres 16, all you have to do is `alter extension pgai update`.

Does this address your concerns, or am I missing something?
