### ISSUE TITLE
Add text-to-sql functionality to PopSQL

### ISSUE THREAD

**Issue by idclevxx** [timescale/pgai#76]
Pardon me for posting this here, but could not find a more suitable repo for it.

Right now, the workflow for developing complex queries involves asking e.g. ChatGPT, then pasting it into a new tab/query in PopSQL. It would be great if text-to-sql functionality was implemented directly to PopSQL, for instance via a new button/icon in the tab window (see screenshot below)

<img width="332" alt="image" src="https://github.com/user-attachments/assets/11a6dcd0-13dc-4942-b3a1-c91a981bdb34">

When the new button is clicked, it could bring up a prompt window where the user asks the question that is then translated into SQL.

**Comment by murrayju** [comment]
@idclevxx we do have something like this in the works, which will be made generally available soon. If you'd like to share your PopSQL organization id, I can give you early access.

Thanks for the feedback!

**Comment by idclevxx** [comment]
> @idclevxx we do have something like this in the works, which will be made generally available soon. If you'd like to share your PopSQL organization id, I can give you early access.
> 
> Thanks for the feedback!

Would love to, but would rather not paste it here, do you have an email/alias I can send it to?

**Comment by murrayju** [comment]
@idclevxx you can send an email to `support@timescale.com` and we'll get it sorted out.
