### ISSUE TITLE
Having trouble installing pgai on brew install postgres and python

### ISSUE THREAD

**Issue by Druhayes** [timescale/pgai#83]
I'm not entirely sure what is going on here.  I doubt it's the makefile with pgai, but I haven't been able to find a solution elsewhere.  

  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/pgai'
make: *** [install] Error 1

**Comment by alejandrodnm** [comment]
Hey @Druhayes sorry for the late response. Pgai by default installs the python part of the extension under `/usr/local/lib/pgai`, it seems that the build script is not able to create the directory. 

You could try the following, creating the file manually with `mkdir -p /usr/local/lib/pgai`

Sorry for the late response, the whole team is focused on a new feature we are going to launch soon.
